version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    GH_TOKEN: c1a3e6c00bf884b2fe6e640f40190b840fa350d6
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run hello-world:nanoserver-1809
            cinst docfx
            dotnet restore
            dotnet build --configuration Release
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n"
            git config --global user.email aryashp4iitk@gmail.com
            git config --global user.name aryashp
            bash releaseDocs.sh
