version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            cinst docfx
            dotnet restore
            dotnet build --configuration Release
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:Token_key):x-oauth-basic@github.com`n"
            git config --global user.email %github_email%
            git config --global user.name "myusername"
            bash releaseDocs.sh
