version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            cinst docfx
            dotnet restore
            dotnet build --configuration Release
            git config --global credential.helper store
            git remote add new-docs "https://aryashp:%Token_key%@github.com/aryashp/Automation.git"
            git config --global user.email "aryashp4iitk@gmail.com"
            git config --global user.name "aryashp"
            bash releaseDocs.sh
            git add .
            git commit -m "Update docs"
            git push new-docs gh-pages --force
