version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run hello-world:nanoserver-1809
            cinst docfx
            dotnet restore
            dotnet build --configuration Release
            git config --global credential.helper store
            git config --global user.email "aryashp4iitk@gmail.com"
            git config --global user.name "aryashp"
            bash releaseDocs.sh
            git remote add new-docs https://aryashp:${Token_key}@github.com/aryashp/Automation-docs.git
            git push new-docs
