version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            cinst docfx
            dotnet restore
            dotnet build --configuration Release
            git config --global credential.helper store
            Add-Content "$env:USERPROFILE\.git-credentials" "https://aryashp:$Token_key@github.com`n"
            git config --global user.email "aryashp4iitk@gmail.com"
            git config --global user.name "aryashp"
            docfx docfx_project/docfx.json
            SOURCE_DIR=$PWD
            TEMP_REPO_DIR=$PWD/../Automation-gh-pages
            echo "Removing temporary doc directory $TEMP_REPO_DIR"
            rm -rf $TEMP_REPO_DIR
            mkdir $TEMP_REPO_DIR
            echo "Cloning the repo with the gh-pages branch"
            git clone https://github.com/aryashp/Automation.git --branch gh-pages $TEMP_REPO_DIR
            echo "Clear repo directory"
            cd $TEMP_REPO_DIR
            git rm -r *
            echo "Copy documentation into the repo"
            cp -r $SOURCE_DIR/docfx_project/_site/* .
            echo "Push the new docs to the remote branch"
            git add . -A
            git commit -m "Update generated documentation"
            git push origin gh-pages
